# Generated by Django 3.2.18 on 2023-05-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_measure_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updateed_at',
        ),
    ]
