# Generated by Django 3.2.18 on 2023-04-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название ингредиента')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('measure_unit', models.CharField(max_length=40, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('image', models.ImageField(help_text='Загрузите сюда картинку вашего рецепта', upload_to='recipes/', verbose_name='Картинка')),
                ('text', models.TextField(help_text='Текстовое описание рецепта', verbose_name='Текстовое описание')),
                ('cooking_time', models.DateTimeField(verbose_name='Время приготовления в минутах')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updateed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(max_length=7, unique=True, verbose_name='Цветовой HEX-код')),
                ('slug', models.SlugField(unique=True, verbose_name='slug тега')),
            ],
        ),
    ]
